template: true
valuesFilePath: ./values.yml

resources:
  {{ range $i, $e := until 100 }}
  - name: git{{$i}}
    type: GitRepo
    configuration:
      path: aarvyved/test-repo
      gitProvider: gitIntegration
      branches:
        include: {{gitBranch}}
  {{ end }}
pipelines:
  - name: pipe
    steps:
      - name: first
        type: Bash
        configuration:
          runtime:
            type: host
        execution:
          onExecute:
            - echo foo
      {{ range $i, $e := until 100 }}
      - name: step{{$i}}
        type: Bash
        configuration:
          runtime:
            type: host
          inputResources:
            - name: git{{$i}}
          inputSteps:
            - name: first
        execution:
          onExecute:
            - echo foo
      {{ end }}
      - name: last
        type: Bash
        configuration:
          runtime:
            type: host
          inputSteps:
            {{ range $i, $e := until 100 }}
            - name: step{{$i}}
            {{ end }}
        execution:
          onExecute:
            - echo foo
